---
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Monitoramento de músicas sendo tocadas em todas as radios do Icecast  #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
- name: Ensure Tableau Monitoring path exists
  file:
    path: '{{ tableau_zabbix_monitoring_script_path }}'
    state: 'directory'
    owner: '{{ tableau_zabbix_monitoring_user }}'
    group: '{{ tableau_zabbix_monitoring_user }}'
    mode: 'u=rwx,g=rx,o=rx'
  tags: 'copy_script'

- name: Copy Tableau Monitoring Script
  template:
    src: 'tableau_check.py.j2'
    dest: '{{ tableau_zabbix_monitoring_script_path }}tableau_check.py'
    owner: '{{ tableau_zabbix_monitoring_user }}'
    group: '{{ tableau_zabbix_monitoring_user }}'
    mode: 'u=rwx,g=rx,o=rx'
  tags: 'copy_script'

- name: Copy Tableau Getter Script
  template:
    src: 'tableau_getter.py.j2'
    dest: '{{ tableau_zabbix_monitoring_script_path }}tableau_getter.py'
    owner: '{{ tableau_zabbix_monitoring_user }}'
    group: '{{ tableau_zabbix_monitoring_user }}'
    mode: 'u=rwx,g=rx,o=rx'
  tags: 'copy_script'


- name: Copy Tableu UserParameter
  template:
    src: 'userparameter_tableau.conf.j2'
    dest: '{{ tableau_zabbix_monitoring_userparameter_path }}userparameter_tableau.conf'
    owner: '{{ tableau_zabbix_monitoring_user }}'
    group: '{{ tableau_zabbix_monitoring_user }}'
    mode: 'u=rw,g=r,o=r'
  notify: 'restart zabbix-agent'
  tags: 'copy_userparameter'

- name: Ensure Tableau Monitoring logging path exists
  file:
    path: '{{ tableau_zabbix_monitoring_log_dir }}'
    state: 'directory'
    owner: '{{ tableau_zabbix_monitoring_user }}'
    group: '{{ tableau_zabbix_monitoring_user }}'
    mode: 'u=rwx,g=rx,o=rx'
  tags: 'copy_script'

- name: Add tableau check crontab
  cron:
    name: "SSL certificate check"
    hour: '{{ tableau_zabbix_monitoring_cron_hour }}'
    minute: '{{ tableau_zabbix_monitoring_cron_minute }}'
    user: '{{ tableau_zabbix_monitoring_user }}'
    job: "/usr/lib/zabbix/modules/tableau/tableau_check.py"
  become: yes
  tags:
    - crontab
    - cron
